### ISSUE TITLE
debuging a Pipeline Run with PTVSD from a notebook VM

### ISSUE THREAD

**Issue by omartin2010** [danielsc/azureml-debug-training#2]
I'm running into a specific issue when trying to attach to the running (waiting process) an AML Compute target. @danielsc 

Here's the output I'm seeing from the log (specifically the azureml-logs/70_driver_log.txt).

> bash: /azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/libtinfo.so.5: no version information available (required by bash)
> bash: /azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/libtinfo.so.5: no version information available (required by bash)
> Starting the daemon thread to refresh tokens in background for process with pid = 145
> Entering Run History Context Manager.
> Launching: python -m ptvsd --host 10.0.0.4 --port 5678 --wait register_best_model.py --hd-step-name hd_train_step --best-model-name pipe_model_testing
> E00400.209: Traceback (most recent call last):
>               File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 269, in process_one_message
>                 msg = self.__message.pop(0)
>             IndexError: pop from empty list
>             
>             During handling of the above exception, another exception occurred:
>             
>             Traceback (most recent call last):
>               File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 170, in _wait_for_message
>                 length_text = headers['Content-Length']
>             KeyError: 'Content-Length'
>             
>             During handling of the above exception, another exception occurred:
>             
>             Traceback (most recent call last):
>               File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 258, in process_messages
>                 self.process_one_message()
>               File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 272, in process_one_message
>                 self._wait_for_message()
>               File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 179, in _wait_for_message
>                 raise InvalidHeaderError('Content-Length not specified in headers')
>             ptvsd.ipcjson.InvalidHeaderError: Content-Length not specified in headers
>             
> 
> Exception in thread ptvsd.Server:
> Traceback (most recent call last):
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 269, in process_one_message
>     msg = self.__message.pop(0)
> IndexError: pop from empty list
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 170, in _wait_for_message
>     length_text = headers['Content-Length']
> KeyError: 'Content-Length'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/wrapper.py", line 521, in process_messages
>     self.process_messages()
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 258, in process_messages
>     self.process_one_message()
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 272, in process_one_message
>     self._wait_for_message()
>   File "/azureml-envs/azureml_545725e1cb9b35bc422730908f3231c4/lib/python3.6/site-packages/ptvsd/ipcjson.py", line 179, in _wait_for_message
>     raise InvalidHeaderError('Content-Length not specified in headers')
> ptvsd.ipcjson.InvalidHeaderError: Content-Length not specified in headers
> 
> 
Any clue what might be the issue? Running the latest version of ptvsd (pulled it from an estimator step, without specifying the version, so likely getting the latest version on the AML compute side), and running VS Code insiders, remoted to the Notebook VM that has the code that's submitted to AMLCompute via an AML pipeline (other steps aren't debugged, just this one which pauses until I connect).

**Comment by omartin2010** [comment]
bump :) @danielsc
